<H1> **Introducción a Python para Big Data** : 🎊

Este notebook te guiará a través de los conceptos fundamentales de Python y la librería Pandas, esenciales para el análisis de datos.

<H3> 1. Primeros pasos con Python 🆎

Comenzaremos con los conceptos básicos de Python, como la creación de variables y la impresión de valores.

In [3]:
# Asignación y tipos de datos
a = 1 + 1
b = "Big Data"

# Imprimir variables en pantalla
print(a)
print(b)

2
Big Data

<H3> 2. Manejo de datos con Pandas ⛵

Pandas es una librería fundamental para trabajar con datos tabulares. Un DataFrame de Pandas es una estructura similar a una hoja de cálculo, con filas y columnas.

Crear un DataFrame

Podemos crear un DataFrame a partir de listas de Python.

In [4]:
# Listas de datos
lista_personajes = ['Luke Skywalker', 'C-3PO', 'Darth Vader']
lista_altura = [172, 167, 202]

# Crear el DataFrame
import pandas as pd

d_star_wars = pd.DataFrame({
    'personaje': lista_personajes,
    'altura': lista_altura
})

# Mostrar el DataFrame y sus tipos de datos
print(d_star_wars)
print("---")
print(d_star_wars.dtypes)

        personaje  altura
0  Luke Skywalker     172
1           C-3PO     167
2     Darth Vader     202
---
personaje    object
altura        int64
dtype: object

<H3> 3. Cargar y explorar un archivo ✈

En el mundo real, los datos rara vez se crean manualmente.
Veamos como cargar un archivo CSV directamente desde una URL.

In [5]:
#Antes de comenzar tenemos que instalar la librería skimpy que me permite conocer información estadística de los datos

!pip install skimpy -q
from skimpy import skim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.6/120.6 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.2/110.2 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 50.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires ipykernel==6.17.1, but you have ipykernel 7.3.0 which is incompatible.
notebook 6.5.7 requires jupyter-client<8,>=5.3.4, but you have jupyter-client 8.10.0 which is incompatible.
jupyter-kernel-gateway 2.5.2 requires jupyter-client<8.0,>=5.2.0, but you have jupyter-client 8.10.0 which is incompatible.

In [6]:
# Cargar un archivo CSV desde una URL
starwars = 'https://raw.githubusercontent.com/fpineyro/homework-0/master/starwars.csv'
d_star_wars_url = pd.read_csv(starwars)

# Explorar el DataFrame
# Muestra las primeras 5 filas
print("Primeras 5 filas:")
print(d_star_wars_url.head(5))

# Muestra el número de filas y columnas (filas, columnas)
print("\nDimensiones del DataFrame:")
print(d_star_wars_url.shape)

# Muestra un resumen estadístico de las variables
print("\nEstadísticas del DataFrame:")
skim(d_star_wars_url)

Primeras 5 filas:
             name  height mass hair_color   skin_color eye_color birth_year  \
0  Luke Skywalker   172.0   77      blond         fair      blue      19BBY
1           C-3PO   167.0   75        NaN         gold    yellow     112BBY
2           R2-D2    96.0   32        NaN  white, blue       red      33BBY
3     Darth Vader   202.0  136       none        white    yellow    41.9BBY
4     Leia Organa   150.0   49      brown        light     brown      19BBY

   gender homeworld species
0    male  Tatooine   Human
1     NaN  Tatooine   Droid
2     NaN     Naboo   Droid
3    male  Tatooine   Human
4  female  Alderaan   Human

Dimensiones del DataFrame:
(87, 10)

Estadísticas del DataFrame:

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 87     │ │ string      │ 9     │                                                          │
│ │ Number of columns │ 10     │ │ float64     │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━┳━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━━━┓  │
│ ┃ column    ┃ NA  ┃ NA %                   ┃ mean    ┃ sd      ┃ p0  ┃ p25   ┃ p50  ┃ p75  ┃ p100  ┃ hist    ┃  │
│ ┡━━━━━━━━━━━╇━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━━━┩  │
│ │ height    │   6 │      6.896551724137931 │   174.4 │   34.77 │  66 │   167 │  180 │  191 │   264 │  ▁ ▁█▂  │  │
│ └───────────┴─────┴────────────────────────┴─────────┴─────────┴─────┴───────┴──────┴──────┴───────┴─────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃          ┃ chars per ┃ words    ┃ total     ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max      ┃ row       ┃ per row  ┃ words     ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━┩  │
│ │ name      │  0 │         0 │ Rey      │ Jabba     │ Ackbar   │ Zam      │      10.3 │      1.8 │       157 │  │
│ │           │    │           │          │ Desilijic │          │ Wesell   │           │          │           │  │
│ │           │    │           │          │ Tiure     │          │          │           │          │           │  │
│ │ mass      │ 28 │ 32.183908 │ 77       │ 1,358     │ 1,358    │ 90       │      2.27 │     0.68 │        59 │  │
│ │           │    │  04597701 │          │           │          │          │           │          │           │  │
│ │ hair_colo │  6 │ 6.8965517 │ none     │ auburn,   │ auburn   │ white    │      4.81 │     0.97 │        84 │  │
│ │ r         │    │  24137931 │          │ white     │          │          │           │          │           │  │
│ │ skin_colo │  2 │ 2.2988505 │ red      │ grey,     │ blue     │ yellow   │      5.94 │      1.2 │       104 │  │
│ │ r         │    │ 747126435 │          │ green,    │          │          │           │          │           │  │
│ │           │    │           │          │ yellow    │          │          │           │          │           │  │
│ │ eye_color │  3 │ 3.4482758 │ red      │ green,    │ black    │ yellow   │      5.04 │     0.99 │        86 │  │
│ │           │    │ 620689653 │          │ yellow    │          │          │           │          │           │  │
│ │ birth_yea │ 44 │ 50.574712 │ 8BBY     │ 41.9BBY   │ 102BBY   │ 92BBY    │      5.23 │     0.49 │        43 │  │
│ │ r         │    │  64367816 │          │           │          │          │           │          │           │  │
│ │ gender    │  3 │ 3.4482758 │ male     │ hermaphro │ female   │ none     │      4.56 │     0.97 │        84 │  │
│ │           │    │ 620689653 │          │ dite      │          │          │           │          │           │  │
│ │ homeworld │ 10 │ 11.494252 │ Tund     │ Cato      │ Alderaan │ Zolan    │      7.14 │     0.98 │        85 │  │
│ │           │    │ 873563218 │          │ Neimoidia │          │          │           │          │           │  │
│ │ species   │  5 │ 5.7471264 │ Dug      │ Yoda's    │ Aleena   │ Zabrak   │      6.18 │     0.98 │        85 │  │
│ │           │    │  36781609 │          │ species   │          │          │           │          │           │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴──────────┴───────────┴──────────┴───────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

<H3>4. Filtrar y seleccionar datos ⛳

Para seleccionar datos específicos de tu DataFrame, usa loc. Con loc puedes seleccionar filas y columnas por sus nombres o etiquetas.


El formato loc[filas, columnas] te permite seleccionar datos usando las etiquetas de filas y columnas.

[0, :]: El primer valor (0) selecciona la fila con la etiqueta 0. Los dos puntos (:) significan todas las columnas.

[:, 'nombre_columna']: Los dos puntos (:) seleccionan todas las filas. El nombre de la columna selecciona una columna específica.

4.1. Seleccionar columnas

In [7]:
# Seleccionar una sola columna
#d_star_wars['personaje']

# Seleccionar múltiples columnas
d_star_wars[['personaje', 'altura']]

        personaje  altura
0  Luke Skywalker     172
1           C-3PO     167
2     Darth Vader     202

4.2. Seleccionar filas

Podemos seleccionar filas basándote en su posición (índice).

Nota: el uso de 0:2 en loc es inclusivo, lo que significa que incluye los índices 0, 1 y 2.

In [8]:
# Seleccionar la primera fila
d_star_wars.loc[2, :]

personaje    Darth Vader
altura               202
Name: 2, dtype: object

In [9]:
# Seleccionar las 3 primeras filas
d_star_wars.loc[0:2, :]

        personaje  altura
0  Luke Skywalker     172
1           C-3PO     167
2     Darth Vader     202

4.3. Filtrar con condiciones

Podemos usar una condición para filtrar filas que cumplan con un criterio específico. Por ejemplo, encontrar todos los personajes cuya altura sea mayor que 200.

In [10]:
# Crear un filtro (devuelve True/False para cada fila)
print(d_star_wars)
filtro_altura = d_star_wars['altura'] > 200
filtro_altura

# Aplicar el filtro para obtener solo los registros que cumplen la condición
d_star_wars.loc[filtro_altura, :]

        personaje  altura
0  Luke Skywalker     172
1           C-3PO     167
2     Darth Vader     202

     personaje  altura
2  Darth Vader     202

4.4. Reemplazar valores

Podemos combinar el filtrado con la asignación para cambiar valores específicos en el DataFrame.

In [11]:
# Reemplazar la altura de Darth Vader por 185
d_star_wars.loc[d_star_wars['personaje'] == 'Darth Vader', 'altura'] = 185

# Verificar el cambio
print(d_star_wars.loc[d_star_wars['personaje'] == 'Darth Vader', :])

     personaje  altura
2  Darth Vader     185

<H3>5. Manejar valores nulos (NaN) ⛎

5.1. Los valores faltantes (NaN) son muy comunes. Es crucial saber cómo identificarlos y manejarlos.

In [12]:
# Identificar nulos por columna
print("Número de nulos en cada columna:")
print(d_star_wars_url.isnull().sum())

Número de nulos en cada columna:
name           0
height         6
mass          28
hair_color     6
skin_color     2
eye_color      3
birth_year    44
gender         3
homeworld     10
species        5
dtype: int64

In [13]:
d_star_wars_url

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species
0,Luke Skywalker,172.0,77,blond,fair,blue,19BBY,male,Tatooine,Human
1,C-3PO,167.0,75,NaN,gold,yellow,112BBY,NaN,Tatooine,Droid
2,R2-D2,96.0,32,NaN,"white, blue",red,33BBY,NaN,Naboo,Droid
3,Darth Vader,202.0,136,none,white,yellow,41.9BBY,male,Tatooine,Human
4,Leia Organa,150.0,49,brown,light,brown,19BBY,female,Alderaan,Human
...,...,...,...,...,...,...,...,...,...,...
82,Rey,NaN,NaN,brown,light,hazel,NaN,female,NaN,Human
83,Poe Dameron,NaN,NaN,brown,light,brown,NaN,male,NaN,Human
84,BB8,NaN,NaN,none,none,black,NaN,none,NaN,Droid
85,Captain Phasma,NaN,NaN,NaN,NaN,NaN,NaN,female,NaN,NaN
86,Padmé Amidala,165.0,45,brown,light,brown,46BBY,female,Naboo,Human

In [14]:
# Reemplazar valores nulos en columnas categóricas
valores_a_rellenar = {'homeworld': 'nulo_world', 'species': 'nulo_species'}

d_star_wars_url.fillna(value=valores_a_rellenar, inplace=True)
print(d_star_wars_url)

              name  height mass hair_color   skin_color eye_color birth_year  \
0   Luke Skywalker   172.0   77      blond         fair      blue      19BBY
1            C-3PO   167.0   75        NaN         gold    yellow     112BBY
2            R2-D2    96.0   32        NaN  white, blue       red      33BBY
3      Darth Vader   202.0  136       none        white    yellow    41.9BBY
4      Leia Organa   150.0   49      brown        light     brown      19BBY
..             ...     ...  ...        ...          ...       ...        ...
82             Rey     NaN  NaN      brown        light     hazel        NaN
83     Poe Dameron     NaN  NaN      brown        light     brown        NaN
84             BB8     NaN  NaN       none         none     black        NaN
85  Captain Phasma     NaN  NaN        NaN          NaN       NaN        NaN
86   Padmé Amidala   165.0   45      brown        light     brown      46BBY

    gender   homeworld       species
0     male    Tatooine         Human
1      NaN    Tatooine         Droid
2      NaN       Naboo         Droid
3     male    Tatooine         Human
4   female    Alderaan         Human
..     ...         ...           ...
82  female  nulo_world         Human
83    male  nulo_world         Human
84    none  nulo_world         Droid
85  female  nulo_world  nulo_species
86  female       Naboo         Human

[87 rows x 10 columns]

In [19]:
#Vemos cual es el promedio de altura
print(d_star_wars_url['height'].mean())

173.93548387096774

In [18]:
# Reemplazar valores nulos en columnas numéricas con el promedio
promedio_altura = d_star_wars_url['height'].mean()


d_star_wars_url['height'] = d_star_wars_url['height'].fillna(promedio_altura)
d_star_wars_url

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,species
0,Luke Skywalker,172.0,77,blond,fair,blue,19BBY,male,Tatooine,Human
1,Darth Vader,202.0,136,none,white,yellow,41.9BBY,male,Tatooine,Human
2,Leia Organa,150.0,49,brown,light,brown,19BBY,female,Alderaan,Human
3,Owen Lars,178.0,120,"brown, grey",light,blue,52BBY,male,Tatooine,Human
4,Beru Whitesun lars,165.0,75,brown,light,blue,47BBY,female,Tatooine,Human
5,Biggs Darklighter,183.0,84,black,light,brown,24BBY,male,Tatooine,Human
6,Obi-Wan Kenobi,182.0,77,"auburn, white",fair,blue-gray,57BBY,male,Stewjon,Human
7,Anakin Skywalker,188.0,84,blond,fair,blue,41.9BBY,male,Tatooine,Human
8,Han Solo,180.0,80,brown,fair,brown,29BBY,male,Corellia,Human
9,Wedge Antilles,170.0,77,brown,fair,hazel,21BBY,male,Corellia,Human
10,Yoda,66.0,17,white,green,brown,896BBY,male,nulo_world,Yoda's species
11,Palpatine,170.0,75,grey,pale,yellow,82BBY,male,Naboo,Human
12,Boba Fett,183.0,78.2,black,fair,brown,31.5BBY,male,Kamino,Human
13,IG-88,200.0,140,none,metal,red,15BBY,none,nulo_world,Droid
14,Bossk,190.0,113,none,green,red,53BBY,male,Trandosha,Trandoshan
15,Lando Calrissian,177.0,79,black,dark,brown,31BBY,male,Socorro,Human
16,Lobot,175.0,79,none,light,blue,37BBY,male,Bespin,Human
17,Ackbar,180.0,83,none,brown mottle,orange,41BBY,male,Mon Cala,Mon Calamari
18,Wicket Systri Warrick,88.0,20,brown,brown,brown,8BBY,male,Endor,Ewok
19,Qui-Gon Jinn,193.0,89,brown,fair,blue,92BBY,male,nulo_world,Human
20,Jar Jar Binks,196.0,66,none,orange,orange,52BBY,male,Naboo,Gungan
21,Darth Maul,175.0,80,none,red,yellow,54BBY,male,Dathomir,Zabrak
22,Ayla Secura,178.0,55,none,blue,hazel,48BBY,female,Ryloth,Twi'lek
23,Mace Windu,188.0,84,none,dark,brown,72BBY,male,Haruun Kal,Human
24,Ki-Adi-Mundi,198.0,82,white,pale,yellow,92BBY,male,Cerea,Cerean
25,Plo Koon,188.0,80,none,orange,black,22BBY,male,Dorin,Kel Dor
26,Luminara Unduli,170.0,56.2,black,yellow,blue,58BBY,female,Mirial,Mirialan
27,Barriss Offee,166.0,50,black,yellow,blue,40BBY,female,Mirial,Mirialan
28,Dooku,193.0,80,white,fair,brown,102BBY,male,Serenno,Human
29,Jango Fett,183.0,79,black,tan,brown,66BBY,male,Concord Dawn,Human
30,Padmé Amidala,165.0,45,brown,light,brown,46BBY,female,Naboo,Human

In [17]:
# Verificar que los nulos fueron reemplazados
skim(d_star_wars_url[['height']])

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 31     │ │ float64     │ 1     │                                                          │
│ │ Number of columns │ 1      │ └─────────────┴───────┘                                                          │
│ └───────────────────┴────────┘                                                                                  │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column      ┃ NA   ┃ NA %    ┃ mean      ┃ sd        ┃ p0   ┃ p25    ┃ p50    ┃ p75   ┃ p100    ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ height      │    0 │       0 │     173.9 │     28.53 │   66 │    170 │    180 │   188 │     202 │  ▁   ▆█  │  │
│ └─────────────┴──────┴─────────┴───────────┴───────────┴──────┴────────┴────────┴───────┴─────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

5.2. Eliminar registros con valores nulos
A veces, en lugar de reemplazar los valores nulos, lo mejor es eliminar por completo las filas o columnas que los contienen. El método dropna() de Pandas te permite hacerlo fácilmente.

Por defecto, dropna() elimina cualquier fila que contenga al menos un valor nulo. Es una forma rápida de limpiar el conjunto de datos si las filas con valores faltantes no son importantes para tu análisis.

In [16]:
# Eliminar las filas con valores nulos y resetear el índice
d_star_wars_url.dropna(inplace=True)
d_star_wars_url.reset_index(drop=True, inplace=True)


skim(d_star_wars_url)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 31     │ │ string      │ 9     │                                                          │
│ │ Number of columns │ 10     │ │ float64     │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column      ┃ NA   ┃ NA %    ┃ mean      ┃ sd        ┃ p0   ┃ p25    ┃ p50    ┃ p75   ┃ p100    ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ height      │    0 │       0 │     173.9 │     28.53 │   66 │    170 │    180 │   188 │     202 │  ▁   ▆█  │  │
│ └─────────────┴──────┴─────────┴───────────┴───────────┴──────┴────────┴────────┴───────┴─────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┓  │
│ ┃           ┃    ┃      ┃          ┃           ┃           ┃            ┃ chars per ┃ words per  ┃ total     ┃  │
│ ┃ column    ┃ NA ┃ NA % ┃ shortest ┃ longest   ┃ min       ┃ max        ┃ row       ┃ row        ┃ words     ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━┩  │
│ │ name      │  0 │    0 │ Yoda     │ Wicket    │ Ackbar    │ Yoda       │      11.1 │        1.8 │        57 │  │
│ │           │    │      │          │ Systri    │           │            │           │            │           │  │
│ │           │    │      │          │ Warrick   │           │            │           │            │           │  │
│ │ mass      │  0 │    0 │ 77       │ 78.2      │ 113       │ 89         │      2.26 │          1 │        31 │  │
│ │ hair_colo │  0 │    0 │ none     │ auburn,   │ auburn,   │ white      │       5.1 │        1.1 │        33 │  │
│ │ r         │    │      │          │ white     │ white     │            │           │            │           │  │
│ │ skin_colo │  0 │    0 │ red      │ brown     │ blue      │ yellow     │      4.81 │          1 │        32 │  │
│ │ r         │    │      │          │ mottle    │           │            │           │            │           │  │
│ │ eye_color │  0 │    0 │ red      │ blue-gray │ black     │ yellow     │      4.94 │          1 │        31 │  │
│ │ birth_yea │  0 │    0 │ 8BBY     │ 41.9BBY   │ 102BBY    │ 92BBY      │      5.23 │          1 │        31 │  │
│ │ r         │    │      │          │           │           │            │           │            │           │  │
│ │ gender    │  0 │    0 │ male     │ female    │ female    │ none       │      4.39 │          1 │        31 │  │
│ │ homeworld │  0 │    0 │ Naboo    │ Concord   │ Alderaan  │ nulo_world │      7.42 │        1.1 │        34 │  │
│ │           │    │      │          │ Dawn      │           │            │           │            │           │  │
│ │ species   │  0 │    0 │ Ewok     │ Yoda's    │ Cerean    │ Zabrak     │      6.06 │        1.1 │        34 │  │
│ │           │    │      │          │ species   │           │            │           │            │           │  │
│ └───────────┴────┴──────┴──────────┴───────────┴───────────┴────────────┴───────────┴────────────┴───────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

<H3> 6. Crear nuevas columnas 🛋

Puedes crear una nueva columna en un DataFrame y asignarle valores basados en una condición. Es una forma muy poderosa de derivar información a partir de los datos existentes.

In [15]:
# Asignamos True si la altura es > 180, de lo contrario, False
d_star_wars['is_tall'] = d_star_wars['altura'] > 180

# Muestra el DataFrame con la nueva columna
print(d_star_wars)

        personaje  altura  is_tall
0  Luke Skywalker     172    False
1           C-3PO     167    False
2     Darth Vader     185     True

<H3> 7. Copiar un DataFrame ©

Cuando realizas cambios en un DataFrame y quieres conservar la versión original, es una buena práctica hacer una copia. Esto te permite manipular la nueva versión sin afectar la original.

In [20]:
#Hacer una copia del DataFrame
d_star_wars_copy = d_star_wars.copy()

# Ahora puedes trabajar con d_star_wars_copy sin afectar el original
d_star_wars_copy

        personaje  altura  is_tall
0  Luke Skywalker     172    False
1           C-3PO     167    False
2     Darth Vader     185     True

************************************************************************************

<H2> Ejercicios 🔰

Aquí hay una serie de ejercicios para aplicar lo que aprendiste. ¡No te frustres si te toma tiempo! La práctica es la clave.

<H3> Ejercicio 1. Carga el archivo heart_disease.csv en un DataFrame llamado d_hd. URL: https://raw.githubusercontent.com/fpineyro/homework-0/master/heart_disease.csv

In [21]:
##Ejercicio 1

import pandas as pd

# Cargar un archivo CSV desde una URL
hd_link = 'https://raw.githubusercontent.com/fpineyro/homework-0/master/heart_disease.csv'
d_hd = pd.read_csv(hd_link)



# Muestra un resumen estadístico de las variables
print("\nEstadísticas del DataFrame:")
skim(d_hd)

Estadísticas del DataFrame:

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 303    │ │ int64       │ 11    │                                                          │
│ │ Number of columns │ 16     │ │ float64     │ 3     │                                                          │
│ └───────────────────┴────────┘ │ string      │ 2     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━┳━━━━━┳━━━━━━┳━━━━━━━━┓  │
│ ┃ column               ┃ NA ┃ NA %               ┃ mean   ┃ sd     ┃ p0  ┃ p25   ┃ p50 ┃ p75 ┃ p100 ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━╇━━━━━╇━━━━━━╇━━━━━━━━┩  │
│ │ age                  │  0 │                  0 │  54.44 │  9.039 │  29 │    48 │  56 │  61 │   77 │ ▁▄▅█▅▁ │  │
│ │ chest_pain           │  0 │                  0 │  3.158 │ 0.9601 │   1 │     3 │   3 │   4 │    4 │ ▁ ▃ ▅█ │  │
│ │ resting_blood_pressu │  0 │                  0 │  131.7 │   17.6 │  94 │   120 │ 130 │ 140 │  200 │ ▃▇█▃▁  │  │
│ │ re                   │    │                    │        │        │     │       │     │     │      │        │  │
│ │ serum_cholestoral    │  0 │                  0 │  246.7 │  51.78 │ 126 │   211 │ 241 │ 275 │  564 │  ▂█▃   │  │
│ │ fasting_blood_sugar  │  0 │                  0 │ 0.1485 │ 0.3562 │   0 │     0 │   0 │   0 │    1 │ █    ▁ │  │
│ │ resting_electro      │  0 │                  0 │ 0.9901 │  0.995 │   0 │     0 │   1 │   2 │    2 │ █    █ │  │
│ │ max_heart_rate       │  0 │                  0 │  149.6 │  22.88 │  71 │ 133.5 │ 153 │ 166 │  202 │  ▂▄██▁ │  │
│ │ exer_angina          │  0 │                  0 │ 0.3267 │ 0.4698 │   0 │     0 │   0 │   1 │    1 │ █    ▄ │  │
│ │ oldpeak              │  0 │                  0 │   1.04 │  1.161 │   0 │     0 │ 0.8 │ 1.6 │  6.2 │  █▃▁▁  │  │
│ │ slope                │  0 │                  0 │  1.601 │ 0.6162 │   1 │     1 │   2 │   2 │    3 │ █  █ ▁ │  │
│ │ num_vessels_flour    │  4 │ 1.3201320132013201 │ 0.6722 │ 0.9374 │   0 │     0 │   0 │   1 │    3 │ █ ▃ ▂▁ │  │
│ │ thal                 │  2 │ 0.6600660066006601 │  4.734 │   1.94 │   3 │     3 │   3 │   7 │    7 │ █   ▁▆ │  │
│ │ heart_disease_severi │  0 │                  0 │ 0.9373 │  1.229 │   0 │     0 │   0 │   2 │    4 │ █▃ ▂▂▁ │  │
│ │ ty                   │    │                    │        │        │     │       │     │     │      │        │  │
│ │ exter_angina         │  0 │                  0 │ 0.3267 │ 0.4698 │   0 │     0 │   0 │   1 │    1 │ █    ▄ │  │
│ └──────────────────────┴────┴────────────────────┴────────┴────────┴─────┴───────┴─────┴─────┴──────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓  │
│ ┃              ┃    ┃      ┃          ┃         ┃        ┃      ┃               ┃ words per    ┃             ┃  │
│ ┃ column       ┃ NA ┃ NA % ┃ shortest ┃ longest ┃ min    ┃ max  ┃ chars per row ┃ row          ┃ total words ┃  │
│ ┡━━━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩  │
│ │ gender       │  0 │    0 │ male     │ female  │ female │ male │          4.64 │            1 │         303 │  │
│ │ has_heart_di │  0 │    0 │ no       │ yes     │ no     │ yes  │          2.46 │            1 │         303 │  │
│ │ sease        │    │      │          │         │        │      │               │              │             │  │
│ └──────────────┴────┴──────┴──────────┴─────────┴────────┴──────┴───────────────┴──────────────┴─────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

<H3> Ejercicio 2. Muestra los primeros 5 y los últimos 5 registros de d_hd.

In [22]:
##Ejercicio 2
d_hd.head(5)
d_hd.tail(5)

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes
299,68,male,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2,0,yes
300,57,male,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3,1,yes
301,57,female,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1,0,yes
302,38,male,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0,0,no

<H3> Ejercicio 3. Selecciona e imprime las columnas age y has_heart_disease.

In [23]:
##Ejercicio 3
d_hd[['age', 'has_heart_disease']]

     age has_heart_disease
0     63                no
1     67               yes
2     67               yes
3     37                no
4     41                no
..   ...               ...
298   45               yes
299   68               yes
300   57               yes
301   57               yes
302   38                no

[303 rows x 2 columns]

<H3> Ejercicio 4. Crea un filtro para encontrar todos los registros donde colesterol (serum_cholestoral) sea mayor que 250.

In [24]:
##Ejercicio 4
filtro_colesterol = d_hd['serum_cholestoral'] > 250

d_hd.loc[filtro_colesterol, :]

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
7,57,female,4,120,354,0,0,163,1,0.6,1,0.0,3.0,0,1,no
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
11,56,female,2,140,294,0,2,153,0,1.3,2,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,57,male,4,110,335,0,0,143,1,3.0,2,1.0,7.0,2,1,yes
281,47,male,3,130,253,0,0,179,0,0.0,1,0.0,3.0,0,0,no
285,58,male,4,114,318,0,1,140,0,4.4,3,3.0,6.0,4,0,yes
291,55,female,2,132,342,0,0,166,0,1.2,1,0.0,3.0,0,0,no
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes

<H3> Ejercicio 5. identificar qué variables tienen valores nulos.

In [25]:
##Ejercicio 5
d_hd.isnull().sum()

age                       0
gender                    0
chest_pain                0
resting_blood_pressure    0
serum_cholestoral         0
fasting_blood_sugar       0
resting_electro           0
max_heart_rate            0
exer_angina               0
oldpeak                   0
slope                     0
num_vessels_flour         4
thal                      2
heart_disease_severity    0
exter_angina              0
has_heart_disease         0
dtype: int64

<H3> Ejercicio 6. Reemplaza los valores nulos de la columna thal por un valor de 999.

In [28]:
##Ejercicio 6
d_hd['thal'] = d_hd['thal'].fillna(999)

d_hd

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
2,67,male,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,1,yes
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no
4,41,female,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,male,1,110,264,0,0,132,0,1.2,2,0.0,7.0,1,0,yes
299,68,male,4,144,193,1,0,141,0,3.4,2,2.0,7.0,2,0,yes
300,57,male,4,130,131,0,0,115,1,1.2,2,1.0,7.0,3,1,yes
301,57,female,2,130,236,0,2,174,0,0.0,2,1.0,3.0,1,0,yes
302,38,male,3,138,175,0,0,173,0,0.0,1,NaN,3.0,0,0,no

<H3> Ejercicio 7. Filtrar por múltiples condiciones:

Utiliza el DataFrame d_hd y filtra para encontrar todos los registros de pacientes que tienen más de 60 años Y un nivel de colesterol (serum_cholestoral) superior a 250.

In [29]:
##Ejercicio 7
filtro_edad = d_hd['age'] > 60
filtro_colesterol = d_hd['serum_cholestoral'] > 250

d_hd.loc[filtro_edad & filtro_colesterol, :]

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
1,67,male,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,1,yes
6,62,female,4,140,268,0,2,160,0,3.6,3,2.0,3.0,3,0,yes
8,63,male,4,130,254,0,2,147,0,1.4,2,1.0,7.0,2,0,yes
32,64,male,3,140,335,0,0,158,0,0.0,1,0.0,3.0,1,0,yes
42,71,female,2,160,302,0,0,162,0,0.4,1,2.0,3.0,0,0,no
44,61,female,4,130,330,0,2,169,0,0.0,1,0.0,3.0,1,0,yes
48,65,female,3,140,417,1,2,157,0,0.8,1,1.0,3.0,0,0,no
70,65,female,3,155,269,0,0,148,0,0.8,1,0.0,3.0,0,0,no
71,67,male,4,125,254,1,0,163,0,0.2,2,2.0,7.0,3,0,yes
72,62,male,4,120,267,0,0,99,1,1.8,2,2.0,7.0,1,1,yes
75,65,female,3,160,360,0,2,151,0,0.8,1,0.0,3.0,0,0,no
83,68,male,3,180,274,1,2,150,1,1.6,2,0.0,7.0,3,1,yes
90,66,male,4,120,302,0,2,151,0,0.4,2,0.0,3.0,0,0,no
94,63,female,3,135,252,0,2,172,0,0.0,1,0.0,3.0,0,0,no
103,71,female,3,110,265,1,2,130,0,0.0,1,1.0,3.0,0,0,no
108,61,male,4,120,260,0,0,140,1,3.6,2,1.0,7.0,2,1,yes
110,61,female,4,145,307,0,2,146,1,1.0,2,0.0,7.0,1,1,yes
114,62,female,3,130,263,0,0,97,0,1.2,2,1.0,7.0,2,0,yes
118,63,male,4,130,330,1,2,132,1,1.8,1,3.0,7.0,3,1,yes
119,65,male,4,135,254,0,2,127,0,2.8,2,1.0,7.0,2,0,yes
121,63,female,4,150,407,0,2,154,0,4.0,2,3.0,7.0,4,0,yes
124,65,male,1,138,282,1,2,174,0,1.4,2,1.0,3.0,1,0,yes
137,62,male,2,120,281,0,2,103,0,1.4,2,1.0,7.0,3,0,yes
143,64,male,3,125,309,0,0,131,1,1.8,2,0.0,7.0,1,1,yes
152,67,female,3,115,564,0,2,160,0,1.6,2,0.0,7.0,0,0,no
155,70,male,4,130,322,0,2,109,0,2.4,2,3.0,3.0,1,0,yes
159,68,male,3,118,277,0,0,151,0,1.0,1,1.0,7.0,0,0,no
161,77,male,4,125,304,0,2,162,1,0.0,1,3.0,3.0,4,1,yes
170,70,male,3,160,269,0,0,112,1,2.9,2,1.0,7.0,3,1,yes
173,62,female,4,140,394,0,2,157,0,1.2,2,0.0,3.0,0,0,no
189,69,male,3,140,254,0,2,146,0,2.0,2,3.0,7.0,2,0,yes
193,62,female,4,138,294,1,0,106,0,1.9,2,3.0,3.0,2,0,yes
195,67,male,4,100,299,0,2,125,1,0.9,2,2.0,3.0,3,1,yes
201,64,female,4,180,325,0,0,154,1,0.0,1,0.0,3.0,0,1,no
203,64,female,3,140,313,0,0,133,0,0.2,1,0.0,7.0,0,0,no
218,64,female,4,130,303,0,0,122,0,2.0,2,2.0,3.0,0,0,no
224,63,female,4,108,269,0,0,169,1,1.8,2,2.0,3.0,1,1,yes
227,67,female,3,152,277,0,0,172,0,0.0,1,1.0,3.0,0,0,no
233,74,female,2,120,269,0,2,121,1,0.2,1,1.0,3.0,0,1,no
252,64,male,4,128,263,0,0,105,1,0.2,2,1.0,7.0,0,1,no
276,66,female,3,146,278,0,2,152,0,0.0,2,1.0,3.0,0,0,no

<H3> Ejercicio 8. Reemplazar valores en una columna:

Selecciona la columna slope del DataFrame d_hd. Reemplaza el valor 1 por el string 'ascendente' y el valor 2 por 'descendente'. Muestra el resultado (no necesitas guardarlo en el DataFrame original).

In [32]:
##Ejercicio 8

d_hd.loc[d_hd['slope'] == 1, 'slope'] = 'ascendente'
d_hd.loc[d_hd['slope'] == 2, 'slope'] = 'descendente'

d_hd

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no
1,67,male,4,160,286,0,2,108,1,1.5,descendente,3.0,3.0,2,1,yes
2,67,male,4,120,229,0,2,129,1,2.6,descendente,2.0,7.0,1,1,yes
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no
4,41,female,2,130,204,0,2,172,0,1.4,ascendente,0.0,3.0,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,male,1,110,264,0,0,132,0,1.2,descendente,0.0,7.0,1,0,yes
299,68,male,4,144,193,1,0,141,0,3.4,descendente,2.0,7.0,2,0,yes
300,57,male,4,130,131,0,0,115,1,1.2,descendente,1.0,7.0,3,1,yes
301,57,female,2,130,236,0,2,174,0,0.0,descendente,1.0,3.0,1,0,yes
302,38,male,3,138,175,0,0,173,0,0.0,ascendente,NaN,3.0,0,0,no

<H3>Ejercicio 9. Crear una nueva columna:

En el DataFrame d_hd, crea una nueva columna llamada is_healthy. Asigna el valor True si el paciente no tiene enfermedad del corazón (es decir, el valor en heart_disease_severity es 0) y False en caso contrario. Muestra el DataFrame con la nueva columna

In [33]:
##Ejercicio 9
d_hd['is_healthy'] = d_hd['heart_disease_severity'] == 0

d_hd

,age,gender,chest_pain,resting_blood_pressure,serum_cholestoral,fasting_blood_sugar,resting_electro,max_heart_rate,exer_angina,oldpeak,slope,num_vessels_flour,thal,heart_disease_severity,exter_angina,has_heart_disease,is_healthy
0,63,male,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,0,no,True
1,67,male,4,160,286,0,2,108,1,1.5,descendente,3.0,3.0,2,1,yes,False
2,67,male,4,120,229,0,2,129,1,2.6,descendente,2.0,7.0,1,1,yes,False
3,37,male,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,0,no,True
4,41,female,2,130,204,0,2,172,0,1.4,ascendente,0.0,3.0,0,0,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45,male,1,110,264,0,0,132,0,1.2,descendente,0.0,7.0,1,0,yes,False
299,68,male,4,144,193,1,0,141,0,3.4,descendente,2.0,7.0,2,0,yes,False
300,57,male,4,130,131,0,0,115,1,1.2,descendente,1.0,7.0,3,1,yes,False
301,57,female,2,130,236,0,2,174,0,0.0,descendente,1.0,3.0,1,0,yes,False
302,38,male,3,138,175,0,0,173,0,0.0,ascendente,NaN,3.0,0,0,no,True

<H3> Ejercicio 10. Eliminar registros con nulos:

Crea una copia del DataFrame d_hd llamada d_hd_clean. Usa el método dropna() para eliminar todos los registros que contengan al menos un valor nulo. Luego, usa status() para verificar que ya no hay valores nulos en d_hd_clean.

In [34]:
##Ejercicio 10
d_hd_clean = d_hd.copy()

d_hd_clean.dropna(inplace=True)
d_hd_clean.reset_index(drop=True, inplace=True)

skim(d_hd_clean)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 299    │ │ int64       │ 10    │                                                          │
│ │ Number of columns │ 16     │ │ float64     │ 3     │                                                          │
│ └───────────────────┴────────┘ │ string      │ 2     │                                                          │
│                                │ bool        │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━┳━━━━━━━━┳━━━━━━┳━━━━━━━━┓  │
│ ┃ column                     ┃ NA  ┃ NA %  ┃ mean    ┃ sd      ┃ p0   ┃ p25  ┃ p50  ┃ p75    ┃ p100 ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━╇━━━━━━━━╇━━━━━━╇━━━━━━━━┩  │
│ │ age                        │   0 │     0 │   54.53 │   9.021 │   29 │   48 │   56 │     61 │   77 │ ▁▄▅█▅▁ │  │
│ │ chest_pain                 │   0 │     0 │   3.161 │  0.9629 │    1 │    3 │    3 │      4 │    4 │ ▁ ▃ ▅█ │  │
│ │ resting_blood_pressure     │   0 │     0 │   131.7 │   17.71 │   94 │  120 │  130 │    140 │  200 │ ▃▇█▃▁  │  │
│ │ serum_cholestoral          │   0 │     0 │   247.1 │   51.91 │  126 │  211 │  242 │  275.5 │  564 │  ▂█▃   │  │
│ │ fasting_blood_sugar        │   0 │     0 │  0.1472 │  0.3549 │    0 │    0 │    0 │      0 │    1 │ █    ▁ │  │
│ │ resting_electro            │   0 │     0 │  0.9967 │  0.9949 │    0 │    0 │    1 │      2 │    2 │ █    █ │  │
│ │ max_heart_rate             │   0 │     0 │   149.5 │   22.95 │   71 │  133 │  153 │  165.5 │  202 │  ▂▄██▁ │  │
│ │ exer_angina                │   0 │     0 │  0.3278 │  0.4702 │    0 │    0 │    0 │      1 │    1 │ █    ▄ │  │
│ │ oldpeak                    │   0 │     0 │   1.052 │   1.164 │    0 │    0 │  0.8 │    1.6 │  6.2 │  █▃▁▁  │  │
│ │ num_vessels_flour          │   0 │     0 │  0.6722 │  0.9374 │    0 │    0 │    0 │      1 │    3 │ █ ▃ ▂▁ │  │
│ │ thal                       │   0 │     0 │   11.38 │    81.2 │    3 │    3 │    3 │      7 │  999 │   █    │  │
│ │ heart_disease_severity     │   0 │     0 │  0.9465 │   1.233 │    0 │    0 │    0 │      2 │    4 │ █▃ ▂▂▁ │  │
│ │ exter_angina               │   0 │     0 │  0.3278 │  0.4702 │    0 │    0 │    0 │      1 │    1 │ █    ▄ │  │
│ └────────────────────────────┴─────┴───────┴─────────┴─────────┴──────┴──────┴──────┴────────┴──────┴────────┘  │
│                                                      bool                                                       │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                            ┃ true            ┃ true rate                     ┃ hist                 ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ is_healthy                        │             161 │                          0.54 │        ▇    █        │  │
│ └───────────────────────────────────┴─────────────────┴───────────────────────────────┴──────────────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━┳━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓  │
│ ┃              ┃    ┃      ┃          ┃         ┃        ┃      ┃               ┃ words per    ┃             ┃  │
│ ┃ column       ┃ NA ┃ NA % ┃ shortest ┃ longest ┃ min    ┃ max  ┃ chars per row ┃ row          ┃ total words ┃  │
│ ┡━━━━━━━━━━━━━━╇━━━━╇━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩  │
│ │ gender       │  0 │    0 │ male     │ female  │ female │ male │          4.65 │            1 │         299 │  │
│ │ has_heart_di │  0 │    0 │ no       │ yes     │ no     │ yes  │          2.46 │            1 │         299 │  │
│ │ sease        │    │      │          │         │        │      │               │              │             │  │
│ └──────────────┴────┴──────┴──────────┴─────────┴────────┴──────┴───────────────┴──────────────┴─────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

************************************************************************************